# -*- coding: utf-8 -*-
"""jacob_globenewswire_rss_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sk2NhhKi79gkyNvjIRS6L0gdB6jAFhAW
"""

import feedparser
import pandas as pd
from datetime import datetime
import requests
from urllib.parse import urlparse
import re

def fetch_rss_news(rss_url, max_items=None):
    """
    Fetch news items from RSS feed and convert to pandas DataFrame.

    Parameters:
    rss_url (str): URL of the RSS feed
    max_items (int): Maximum number of items to fetch (None for all)

    Returns:
    pandas.DataFrame: DataFrame containing news items
    """

    try:
        print(f"Fetching RSS feed from: {rss_url}")

        # Parse the RSS feed
        feed = feedparser.parse(rss_url)

        if feed.bozo:
            print("Warning: Feed may have parsing issues")

        # Check if feed was successfully parsed
        if not hasattr(feed, 'entries') or len(feed.entries) == 0:
            print("No entries found in the RSS feed")
            return pd.DataFrame()

        print(f"Found {len(feed.entries)} news items")

        # Extract news items
        news_items = []

        for i, entry in enumerate(feed.entries):
            if max_items and i >= max_items:
                break

            try:
                # Extract publication date
                pub_date = None
                if hasattr(entry, 'published_parsed') and isinstance(entry.published_parsed, tuple):
                    pub_date = datetime(*entry.published_parsed[:6])
                elif hasattr(entry, 'updated_parsed') and isinstance(entry.updated_parsed, tuple):
                    pub_date = datetime(*entry.updated_parsed[:6])
                elif hasattr(entry, 'published'):
                    # Try to parse published date string
                    try:
                        pub_date = datetime.strptime(entry.published, '%a, %d %b %Y %H:%M:%S %z')
                    except:
                        pub_date = entry.published

                # Clean up summary/description
                summary = ""
                if hasattr(entry, 'summary'):
                    summary = entry.summary
                elif hasattr(entry, 'description'):
                    summary = entry.description

                # Remove HTML tags from summary
                summary = re.sub(r'<[^>]+>', '', summary).strip()

                # Extract author/source
                author = ""
                if hasattr(entry, 'author'):
                    author = entry.author
                elif hasattr(entry, 'source'):
                    author = entry.source.get('title', '')

                # Extract categories/tags
                categories = []
                if hasattr(entry, 'tags'):
                    categories = [tag.term for tag in entry.tags]

                # Create news item dictionary
                news_item = {
                    'title': getattr(entry, 'title', ''),
                    'link': getattr(entry, 'link', ''),
                    'published_date': pub_date,
                    'author': author,
                    'summary': summary,
                    'categories': ', '.join(categories) if categories else '',
                    'guid': getattr(entry, 'id', getattr(entry, 'guid', '')),
                }

                # Add any additional fields that might be present
                if hasattr(entry, 'media_content'):
                    news_item['media_url'] = entry.media_content[0]['url'] if entry.media_content else ''

                news_items.append(news_item)

            except Exception as e:
                print(f"Error processing entry {i}: {str(e)}")
                continue

        # Create DataFrame
        df = pd.DataFrame(news_items)

        # Sort by publication date (newest first)
        if 'published_date' in df.columns and not df['published_date'].isna().all():
            df = df.sort_values('published_date', ascending=False).reset_index(drop=True)

        print(f"Successfully processed {len(df)} news items")

        # Save to CSV
        timestamp = datetime.now().strftime('%Y%m%d_%H%M')
        filename = f"energy_news_{timestamp}.csv"
        df.to_csv(filename, index=False)
        print(f"Saved news to {filename}")

        return df

    except Exception as e:
        print(f"Error fetching RSS feed: {str(e)}")
        return pd.DataFrame()

if __name__ == "__main__":
    rss_url = "https://www.globenewswire.com/RssFeed/industry/1-Energy/feedTitle/GlobeNewswire%20-%20Industry%20News%20on%20Energy"
    news_df = fetch_rss_news(rss_url, max_items=50)  # Limit to 50 items for example
    print(news_df.head())