# -*- coding: utf-8 -*-
"""jacob_yfinance_prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLfeon-I-56tcXgNiIbOOLRcQqrexrgD

"""

import pandas as pd
import logging
import os
import sys
from datetime import datetime, time, timedelta
from typing import List, Dict, Optional, Tuple
import yfinance as yf
from openai import OpenAI
from dotenv import load_dotenv
import json
import time as time_module

# Add project root to path (assuming utils are in a parent directory)
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Ensure these imports are correct based on your project structure
# If you don't need OpenAI for this specific task (as tickers are already present),
# you could potentially remove the openai client import if it causes issues,
# but it's part of your existing class.
try:
    from utils.ai.openai_util import client
except ImportError:
    # Fallback if openai_util isn't strictly necessary for this script's purpose
    # or if you don't have an OpenAI client setup when running this specific script.
    # If extract_ticker_from_company is never called, this won't be an issue.
    print("Warning: Could not import utils.ai.openai_util. If not extracting tickers, this is fine.")
    client = None # Or set up a mock client if absolutely necessary for instantiation

from utils.date.date_adjuster import get_previous_trading_day, get_next_trading_day
# Assuming you don't need news_db_util and price_move_db_util for this specific task
# from utils.db.news_db_util import get_news_df, update_news_tickers
# from utils.db.price_move_db_util import store_price_move, PriceMove


# Load environment variables
load_dotenv()

# Configure logging (same as your original script)
os.makedirs('logs', exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/backfill_db.log'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


# Reuse your DatabaseBackfillProcessor class
class DatabaseBackfillProcessor:
    def __init__(self):
        # Only initialize openai_client if 'client' was successfully imported and is not None
        self.openai_client = client if client else None
        self.index_symbol = 'SPY'  # S&P 500 ETF as market index
        self.stats = {
            'total_news': 0,
            'with_ticker': 0,
            'without_ticker': 0,
            'ticker_extracted': 0,
            'price_moves_calculated': 0,
            'price_moves_stored_db': 0,
            'price_moves_stored_csv': 0,
            'errors': 0
        }

    # You can remove or keep extract_ticker_from_company as it won't be used
    # for news that already has tickers, but it's part of the class you provided.
    def extract_ticker_from_company(self, company_name: str, news_text: str = "") -> Optional[str]:
        """Extract ticker symbol from company name using OpenAI."""
        if not self.openai_client:
            logger.error("OpenAI client not initialized. Cannot extract tickers.")
            return None
        try:
            if not company_name:
                return None

            text = f"Company: {company_name}"
            if news_text:
                text += f" News: {news_text[:500]}"

            response = self.openai_client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {
                        "role": "system",
                        "content": "Extract publicly traded companies from news text. Return JSON with 'tickers' and 'companies' arrays. Example: {\"tickers\": [\"AAPL\", \"MSFT\"], \"companies\": [\"Apple Inc\", \"Microsoft Corporation\"]}. If no companies found, return {\"tickers\": [], \"companies\": []}."
                    },
                    {
                        "role": "user",
                        "content": f"Extract company tickers and names from this text: {text}"
                    }
                ],
                max_tokens=100,
                temperature=0
            )

            result = response.choices[0].message.content
            try:
                if result is not None and isinstance(result, str):
                    parsed = json.loads(result)
                    tickers = parsed.get('tickers', [])
                    return tickers[0] if tickers else None
                else:
                    logger.warning(f"OpenAI response content is None or not a string: {result}")
                    return None
            except json.JSONDecodeError:
                logger.warning(f"Failed to parse OpenAI response: {result}")
                return None

        except Exception as e:
            logger.error(f"Error extracting ticker for {company_name}: {e}")
            return None

    def get_price_data(self, ticker: str, published_date: datetime) -> Optional[Dict]:
        """Get price data for ticker around the published date."""
        try:
            # Handle timezone-aware datetime (original logic)
            if isinstance(published_date, datetime) and published_date.tzinfo is None:
                published_date = published_date.replace(tzinfo=None)

            pub_time = published_date.time()
            pub_date = published_date.date()

            # Determine market timing based on publication time
            if time(9, 30) <= pub_time < time(16, 0):
                market = 'regular_market'
            elif time(16, 0) <= pub_time:
                market = 'after_market'
            elif time(0, 0) <= pub_time < time(9, 30):
                market = 'pre_market'
            else:
                market = 'regular_market'

            # Get trading days
            previous_trading_day = get_previous_trading_day(pub_date)
            next_trading_day = get_next_trading_day(pub_date)

            # Format dates for yfinance
            yf_prev_date = previous_trading_day.strftime('%Y-%m-%d')
            yf_today_date = pub_date.strftime('%Y-%m-%d')
            yf_next_date = next_trading_day.strftime('%Y-%m-%d')

            logger.debug(f"Getting price data for {ticker} on {yf_today_date}, market: {market}")

            # Download price data - ADDED auto_adjust=True to address FutureWarning
            data = yf.download(ticker, start=yf_prev_date, end=yf_next_date, interval='1d', auto_adjust=True)
            index_data = yf.download(self.index_symbol, start=yf_prev_date, end=yf_next_date, interval='1d', auto_adjust=True)

            if data is None or index_data is None or data.empty or index_data.empty:
                logger.warning(f"No price data available for {ticker} between {yf_prev_date} and {yf_next_date}. Data empty.")
                return None

            # Check if relevant dates exist in the downloaded data
            # This handles cases where yfinance returns data but not for the exact requested date
            if market == 'pre_market':
                if data is None or index_data is None or yf_prev_date not in data.index or yf_today_date not in data.index:
                    logger.warning(f"Missing required dates for {ticker} (pre_market): {yf_prev_date}, {yf_today_date}")
                    return None
                begin_price = float(data.loc[yf_prev_date, 'Close'].iloc[0])
                end_price = float(data.loc[yf_today_date, 'Open'].iloc[0])
                index_begin_price = float(index_data.loc[yf_prev_date, 'Close'].iloc[0])
                index_end_price = float(index_data.loc[yf_today_date, 'Open'].iloc[0])
            elif market == 'regular_market':
                if data is None or index_data is None or yf_today_date not in data.index:
                    logger.warning(f"Missing required date for {ticker} (regular_market): {yf_today_date}")
                    return None
                begin_price = float(data.loc[yf_today_date, 'Open'].iloc[0])
                end_price = float(data.loc[yf_today_date, 'Close'].iloc[0])
                index_begin_price = float(index_data.loc[yf_today_date, 'Open'].iloc[0])
                index_end_price = float(index_data.loc[yf_today_date, 'Close'].iloc[0])
            else:  # after_market
                if data is None or index_data is None or yf_today_date not in data.index or yf_next_date not in data.index:
                    logger.warning(f"Missing required dates for {ticker} (after_market): {yf_today_date}, {yf_next_date}")
                    return None
                begin_price = float(data.loc[yf_today_date, 'Close'].iloc[0])
                end_price = float(data.loc[yf_next_date, 'Open'].iloc[0])
                index_begin_price = float(index_data.loc[yf_today_date, 'Close'].iloc[0])
                index_end_price = float(index_data.loc[yf_next_date, 'Open'].iloc[0])

            # Calculate price changes
            price_change = end_price - begin_price
            index_price_change = index_end_price - index_begin_price

            price_change_percentage = (price_change / begin_price) * 100 if begin_price != 0 else 0
            index_price_change_percentage = (index_price_change / index_begin_price) * 100 if index_begin_price != 0 else 0

            volume = float(data.loc[yf_today_date, 'Volume'].iloc[0]) if data is not None and yf_today_date in data.index else 0

            return {
                'begin_price': begin_price,
                'end_price': end_price,
                'index_begin_price': index_begin_price,
                'index_end_price': index_end_price,
                'price_change': price_change,
                'price_change_percentage': price_change_percentage,
                'index_price_change': index_price_change,
                'index_price_change_percentage': index_price_change_percentage,
                'daily_alpha': price_change_percentage - index_price_change_percentage,
                'actual_side': 'UP' if price_change_percentage >= 0 else 'DOWN',
                'volume': volume,
                'market': market
            }

        except KeyError as ke:
            logger.error(f"KeyError for {ticker} on {published_date.strftime('%Y-%m-%d')}: {ke}. This might mean missing 'Open', 'Close', or 'Volume' data for the date.")
            return None
        except IndexError as ie:
            logger.error(f"IndexError for {ticker} on {published_date.strftime('%Y-%m-%d')}: {ie}. Data might be malformed or missing expected date indices.")
            return None
        except Exception as e:
            logger.error(f"Error getting price data for {ticker} on {published_date.strftime('%Y-%m-%d')}: {e}")
            return None

def process_csv_for_price_moves(csv_filepath: str, output_dir: str = 'data') -> pd.DataFrame:
    """
    Loads a CSV, processes each news item to get price moves using the
    DatabaseBackfillProcessor's logic, and saves the results.
    """
    logger.info(f"Starting CSV processing for {csv_filepath}...")
    processor = DatabaseBackfillProcessor()
    
    try:
        news_df = pd.read_csv(csv_filepath)
        # If 'tickers' column exists, parse and explode it
        if 'tickers' in news_df.columns:
            import ast
            news_df['tickers'] = news_df['tickers'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
            news_df = news_df.explode('tickers')
            news_df = news_df.rename(columns={'tickers': 'ticker'})
        # Ensure 'published_date' is datetime object
        if 'published_date' not in news_df.columns:
            logger.warning("Input CSV is missing 'published_date' column. Cannot proceed.")
            return pd.DataFrame()
        news_df['published_date'] = pd.to_datetime(news_df['published_date'], errors='coerce')
        logger.info(f"Loaded {len(news_df)} news items from CSV after exploding tickers.")

        price_moves_results = []
        for index, row in news_df.iterrows():
            ticker = row.get('yf_ticker')
            if not ticker:
                ticker = row.get('ticker')
            published_date = row['published_date']
            # Now check if it's a valid datetime
            if not isinstance(published_date, datetime) or pd.isnull(published_date):
                logger.warning(f"Skipping row {index} due to missing or invalid published_date: {row.get('id')}")
                continue
            if not ticker:
                logger.warning(f"Skipping row {index} due to missing ticker: {row.get('id')}")
                continue
            date_str = published_date.strftime('%Y-%m-%d %H:%M:%S')
            logger.info(f"Processing {ticker} on {date_str}")
            price_data = processor.get_price_data(ticker, published_date)
            if price_data:
                combined_data = {
                    'news_id': row.get('id', index),
                    'title': row.get('title', ''),
                    'description': row.get('content', ''),
                    'link': row.get('link', ''),
                    'company': row.get('company', ''),
                    'ticker': ticker,
                    'published_date': published_date,
                    'publisher': row.get('publisher', ''),
                    'language': row.get('language', ''),
                    **price_data
                }
                price_moves_results.append(combined_data)
                processor.stats['price_moves_calculated'] += 1
            else:
                logger.warning(f"Could not get price data for {ticker} on {date_str}. Skipping.")
                processor.stats['errors'] += 1
            time_module.sleep(0.1)
        results_df = pd.DataFrame(price_moves_results)
        if not results_df.empty:
            # Save to main /data directory at project root
            project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            output_dir_main = os.path.join(project_root, 'data')
            os.makedirs(output_dir_main, exist_ok=True)
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'energy_news_price_moves_{timestamp}.csv'
            output_filepath = os.path.join(output_dir_main, output_filename)
            results_df.to_csv(output_filepath, index=False)
            logger.info(f"Saved {len(results_df)} price moves to {output_filepath}")
            print(f"Saved price moves to {output_filepath}")
            processor.stats['price_moves_stored_csv'] = len(results_df)
        else:
            logger.warning("No price moves were calculated for any news items.")
        return results_df

    except Exception as e:
        logger.error(f"An error occurred during CSV processing: {e}")
        logger.exception("Full traceback:")
        return pd.DataFrame()

if __name__ == "__main__":
    import sys, glob, os
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    else:
        files = sorted([f for f in glob.glob("*_news_with_tickers_*.csv")], reverse=True)
        if files:
            csv_file = files[0]
            print(f"Using latest file: {csv_file}")
        else:
            raise FileNotFoundError("No *_news_with_tickers_*.csv file found. Please provide a CSV filename as an argument.")
    
    # Extract industry prefix from filename
    base = os.path.basename(csv_file)
    if "_news_" in base:
        industry_prefix = base.split("_news_")[0]
    else:
        industry_prefix = "news"

    # Run the processing
    def process_csv_for_price_moves_with_industry(csv_filepath: str, output_dir: str = 'data', industry_prefix: str = "news") -> pd.DataFrame:
        logger.info(f"Starting CSV processing for {csv_filepath}...")
        processor = DatabaseBackfillProcessor()
        try:
            news_df = pd.read_csv(csv_filepath)
            # If 'tickers' column exists, parse and explode it
            if 'tickers' in news_df.columns:
                import ast
                news_df['tickers'] = news_df['tickers'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])
                news_df = news_df.explode('tickers')
                news_df = news_df.rename(columns={'tickers': 'ticker'})
            # Ensure 'published_date' is datetime object
            if 'published_date' not in news_df.columns:
                logger.warning("Input CSV is missing 'published_date' column. Cannot proceed.")
                return pd.DataFrame()
            news_df['published_date'] = pd.to_datetime(news_df['published_date'], errors='coerce')
            logger.info(f"Loaded {len(news_df)} news items from CSV after exploding tickers.")

            price_moves_results = []
            for index, row in news_df.iterrows():
                ticker = row.get('yf_ticker')
                if not ticker:
                    ticker = row.get('ticker')
                published_date = row['published_date']
                # Now check if it's a valid datetime
                if not isinstance(published_date, datetime) or pd.isnull(published_date):
                    logger.warning(f"Skipping row {index} due to missing or invalid published_date: {row.get('id')}")
                    continue
                if not ticker:
                    logger.warning(f"Skipping row {index} due to missing ticker: {row.get('id')}")
                    continue
                date_str = published_date.strftime('%Y-%m-%d %H:%M:%S')
                logger.info(f"Processing {ticker} on {date_str}")
                price_data = processor.get_price_data(ticker, published_date)
                if price_data:
                    combined_data = {
                        'news_id': row.get('id', index),
                        'title': row.get('title', ''),
                        'description': row.get('content', ''),
                        'link': row.get('link', ''),
                        'company': row.get('company', ''),
                        'ticker': ticker,
                        'published_date': published_date,
                        'publisher': row.get('publisher', ''),
                        'language': row.get('language', ''),
                        **price_data
                    }
                    price_moves_results.append(combined_data)
                    processor.stats['price_moves_calculated'] += 1
                else:
                    logger.warning(f"Could not get price data for {ticker} on {date_str}. Skipping.")
                    processor.stats['errors'] += 1
                time_module.sleep(0.1)
            results_df = pd.DataFrame(price_moves_results)
            if not results_df.empty:
                # Save to main /data directory at project root
                project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                output_dir_main = os.path.join(project_root, 'data')
                os.makedirs(output_dir_main, exist_ok=True)
                timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                output_filename = f'{industry_prefix}_news_price_moves_{timestamp}.csv'
                output_filepath = os.path.join(output_dir_main, output_filename)
                results_df.to_csv(output_filepath, index=False)
                logger.info(f"Saved {len(results_df)} price moves to {output_filepath}")
                print(f"Saved price moves to {output_filepath}")
                processor.stats['price_moves_stored_csv'] = len(results_df)
            else:
                logger.warning("No price moves were calculated for any news items.")
            return results_df
        except Exception as e:
            logger.error(f"An error occurred during CSV processing: {e}")
            logger.exception("Full traceback:")
            return pd.DataFrame()

    final_price_moves_df = process_csv_for_price_moves_with_industry(csv_file, industry_prefix=industry_prefix)

    if not final_price_moves_df.empty:
        logger.info("\nSample of calculated price moves:")
        sample_cols = ['company', 'ticker', 'published_date', 'price_change_percentage', 'actual_side']
        print(final_price_moves_df[sample_cols].head())
