# -*- coding: utf-8 -*-
"""ticker_extractor_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpP8QCHSb5GfcKQvDwvCTI-8g6_qlhT9
"""

import pandas as pd
import openai
import json
import time
import re
import os
from dotenv import load_dotenv
from datetime import datetime
import glob
import sys


def extract_tickers_from_news(df, api_key, title_col='title', content_col='summary'):
    """
    Extract Yahoo Finance ticker symbols and company names from news dataframe using OpenAI.

    Parameters:
    df (pd.DataFrame): News dataframe
    api_key (str): OpenAI API key
    title_col (str): Column name for titles
    content_col (str): Column name for content/summary

    Returns:
    pd.DataFrame: Original dataframe with 'tickers' and 'companies' columns added
    """

    # Initialize OpenAI client with the provided API key
    client = openai.OpenAI(api_key=api_key)

    # Copy dataframe
    result_df = df.copy()
    ticker_lists = []
    company_lists = []

    print(f"Processing {len(df)} news items...")

    for i, row in df.iterrows():
        # Combine title and content
        title = str(row.get(title_col, ''))
        content = str(row.get(content_col, ''))
        text = f"{title} {content}".strip()

        # Skip if no text
        if not text:
            ticker_lists.append([])
            company_lists.append([])
            continue

        try:
            # Call OpenAI API
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {
                        "role": "system",
                        "content": "Extract publicly traded companies from news text. Return JSON with 'tickers' and 'companies' arrays. Example: {\"tickers\": [\"AAPL\", \"MSFT\"], \"companies\": [\"Apple Inc\", \"Microsoft Corporation\"]}. If no companies found, return {\"tickers\": [], \"companies\": []}."
                    },
                    {
                        "role": "user",
                        "content": f"Extract company tickers and names from this news text: {text[:1000]}"  # Limit text length
                    }
                ],
                max_tokens=100,
                temperature=0
            )

            # Parse response
            message_content = response.choices[0].message.content
            if message_content is not None:
                content = message_content.strip()
            else:
                content = ""

            try:
                # Try to parse as JSON
                result = json.loads(content)
                if isinstance(result, dict) and 'tickers' in result and 'companies' in result:
                    # Clean tickers and companies
                    clean_tickers = [ticker.upper() for ticker in result['tickers'] if isinstance(ticker, str) and ticker.isalpha()]
                    clean_companies = [company.strip() for company in result['companies'] if isinstance(company, str)]
                    ticker_lists.append(clean_tickers)
                    company_lists.append(clean_companies)
                else:
                    ticker_lists.append([])
                    company_lists.append([])
            except json.JSONDecodeError:
                # Fallback: extract ticker-like patterns
                ticker_pattern = r'\b[A-Z]{1,5}\b'
                matches = re.findall(ticker_pattern, content)
                ticker_lists.append(matches)
                company_lists.append([])

        except Exception as e:
            print(f"Error processing row {i}: {e}")
            ticker_lists.append([])
            company_lists.append([])

        # Progress update
        if (i + 1) % 10 == 0:
            print(f"Processed {i + 1}/{len(df)} items")

        # Rate limiting
        time.sleep(0.5)

    # Add tickers and companies to dataframe
    result_df['tickers'] = ticker_lists
    result_df['companies'] = company_lists

    print(f"Extraction complete! Found companies in {sum(1 for t in ticker_lists if t)} out of {len(df)} items")
    return result_df

# Load environment variables from .env file
load_dotenv()

# Prompt for or find the latest news_*.csv file
if len(sys.argv) > 1:
    input_csv = sys.argv[1]
else:
    # Only use files that do NOT contain 'with_tickers' in the name
    files = sorted([f for f in glob.glob("*_news_*.csv") if "with_tickers" not in f], reverse=True)
    if files:
        input_csv = files[0]
        print(f"Using latest file: {input_csv}")
    else:
        raise FileNotFoundError("No raw news_*.csv file found. Please provide a CSV filename as an argument.")

# Load the news data
news_df = pd.read_csv(input_csv)

# Extract industry prefix from input filename
base = os.path.basename(input_csv)
if "_news_" in base:
    industry_prefix = base.split("_news_")[0]
else:
    industry_prefix = "news"

# Limit to first 500 news items
news_df = news_df.head(500)
#remove if wanting to run whole dataset overnight

# Extract tickers (API key loaded from environment)
API_KEY = os.getenv("API_KEY")
result = extract_tickers_from_news(news_df, API_KEY, title_col='title', content_col='summary')

# Save results with timestamp
timestamp = datetime.now().strftime('%Y%m%d_%H%M')
filename = f"{industry_prefix}_news_with_tickers_{timestamp}.csv"
result.to_csv(filename, index=False)
print(f"Saved results to {filename}")

# Display results
print("\nResults:")
for i, row in result.iterrows():
     print(f"Title: {row['title']}")
     print(f"Tickers: {row['tickers']}")
     print(f"Companies: {row['companies']}")
     print("-" * 40)

